# Social aspects of collaboration and data policies

## Learning Objectives

In this lesson, you will learn:

- Technique for group facilitation
- Policies surrounding data, authorship and community participation

## Resources

- [Meeting facilitation technique](files/MtgFacilitation.pdf)

Example Codes of Conduct

- [Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
- [Mozilla Science Code of Conduct](https://science.mozilla.org/code-of-conduct)
- [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/)
- [Ecological Society of America Code of Conduct](https://www.esa.org/esa/code-of-conduct-for-esa-events/)
- [American Geophysical Union Code of Conduct](https://fallmeeting.agu.org/2018/agu-meetings-code-of-conduct/)

Policy Templates: 

- [Authorship Policy](files/template-authorship-policy-ADC-training.docx)
- [Data Policy](files/template-data-policy-ADC-training.docx)


## References

- [Cheruvelil, K. S., Soranno, P. A., Weathers, K. C., Hanson, P. C., Goring, S. J., Filstrup, C. T., & Read, E. K. (2014). Creating and maintaining high-performing collaborative research teams: The importance of diversity and interpersonal skills. Frontiers in Ecology and the Environment, 12(1), 31-38. DOI: 10.1890/130001](https://esajournals.onlinelibrary.wiley.com/doi/epdf/10.1890/130001)
