---
format: html
---

## Reproducibility activity using LEGO速

### Learning Objectives {.unnumbered}

- Illustrate elements of good reproducibility through the medium of LEGO速
- Discuss what is needed and what is not needed for good reproducibility

::: callout-note
## Acknowledgements
This activity is largely based on the [LEGO速 Metadata for Reproducibility game pack](http://eprints.gla.ac.uk/196477/), which was developed by [Mary Donaldson](https://orcid.org/0000-0002-1936-3499) and [Matt Mahon](https://orcid.org/0000-0001-8950-8422).
:::

## Getting started

::: callout-tip
#### Setup

1.  Gather into small groups
2.  Get LEGO速 blocks and worksheets (instructions + metadata documentation)
3.  Follow directions on worksheets
:::

At the end, we will discuss as a group.

## Discussion

<details>

<summary>Discussion Questions</summary>

-   Did you find this a simple way to document your process?
-   Was there anything you found difficult to capture?
-   Did those replicating the builds find it straightforward to follow?
-   Did you encounter any ambiguity in the instructions?

</details>

