### Developing a Code of Conduct

Whether you are joining a lab group or establishing a new collaboration, articulating a set of shared agreements about how people in the group will treat each other will help create the conditions for successful collaboration. If agreements or a code of conduct do not yet exist, invite a conversation among all members to create them. Consider both the behaviors you want to encourage and those that will not be tolerated. 

The Openscapes Code of Conduct, for example, states: Be respectful, honest, inclusive, accommodating, appreciative, and open to learning from everyone else. Do not attack, demean, disrupt, harass, or threaten others or encourage such behavior. Check out these additional examples: [NCEAS Code of Conduct](https://live-ncea-ucsb-edu-v01.pantheonsite.io/sites/default/files/2020-02/NCEAS_Code-of-Conduct_2019.pdf), [Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html), [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/), [Ecological Society of America Code of Conduct](https://www.esa.org/esa/code-of-conduct-for-esa-events/) and the [Battelle Code of Conduct](sections/working-at-NEON.Rmd) linked in Section 2.2: Code of Conduct

We return to the following principles for collaboration over and over: 

- Welcome and honor all voices, make space for equitable and genuine participation
- Listen for understanding, speak to be understood (in contrast to “predatory listening,” listening for the weakness in another’s argument)
- Stay open, curious, and committed to learning (as opposed to closed and committed to being right)
- Actively work to bridge across differences (e.g., unpack assumptions, avoid jargon, invite new perspectives)
- Bring humor
- Be flexible, go with the flow
- Move at the speed of trust (a core principle of the Black Lives Matter movement)
- Be present
- Trust that dialogue will take us deeper (and that struggle can be productive)




