## Navigating Challenges in Collaborative Science

### Learning objectives

In this lesson you will learn

* Best practices for navigating authorship, credit, and power dynamics in team science collaborations

* Best practices for data sharing in team science collaborations

### Authorship and credit

Most people who have participated in group projects will recognize that maintaining clear channels of communication among team members can be a big challenge. At NCEAS we encourage scientists to discuss authorship, credit and data sharing early and often. Many publications resulting from NCEAS work are authored by large groups of individuals. These individuals may not know each other well at the beginning of the project, and they may represent fields which have diverse views on authorship and data sharing.

Check the "Publication" section of the Ecological Society of America's [Code of Ethics](https://www.esa.org/about/code-of-ethics/) as a starting point for discussions about co-authorship. NCEAS endorses these principles in establishing authorship. You might also wish to check guidelines published by the journal(s) to which you anticipate submitting your work.

We recommend you write an authorship agreement for your group early in the project and refer to it for each product. A template is provided in the Resources section below.

### Data sharing

NCEAS is committed to making ecological data available to the broader scientific community, and we expect that NCEAS projects adhere to our data policy, which can be found [here](https://www.nceas.ucsb.edu/datapolicy). As with authorship, we also encourage groups to engage in open, honest conversation about data sharing early in their collaboration. 

In addition, there may be legal or policy considerations related to data sharing for your project. You can [learn more here](https://www.dataone.org/best-practices/sharing-data-legal-and-policy-considerations). 

We recommend you write a data sharing agreement for your group early on and revisit it periodically throughout the project. A template is provided in the Resources section below.  

### Resources

[Authorship template](https://drive.google.com/open?id=1ffIv6GZjuS6FHRcxAk38ZRKqeIN8bNJZ)

Cheruvelil, Kendra S., et al. "[Creating and maintaining high‐performing collaborative research teams: the importance of diversity and interpersonal skills.](https://doi.org/10.1890/130001)" Frontiers in Ecology and the Environment 12.1 (2014): 31-38.

[DataOne Best Practices Database](https://www.dataone.org/best-practices)

[Data sharing template](https://drive.google.com/open?id=1Ft3mlh3yoXMlgw21qpVP4vWjVqK8-vRo)

Frassl, Marieke A et al. "Ten simple rules for collaboratively writing a multi-authored paper." *PLoS computational biology* vol. 14,11 e1006508. 15 Nov. 2018, [doi:10.1371/journal.pcbi.1006508](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006508)

Goring, Simon J., et al. "[Improving the culture of interdisciplinary collaboration in ecology by expanding measures of success.](https://doi.org/10.1890/120370)" Frontiers in Ecology and the Environment 12.1 (2014): 39-47.

