---
title: "Community Data Resources"
author: "Noor Johnson"
date: "3/28/2022"

bibliography: 202203_ASSW_Training.bib
---

### References

Burrage, Rachel L. 2020. “Concerning Disconnects: The Place of
Secondary Analysis in Indigenous Inquiry.” In New Directions in
Theorizing Qualitative Research, eds. Norman K. Denzin and James
Salvo. Gorham, ME: Myers Education Press, 23–38.

Gardiner, G, Thorpe, K. 2014. “The Aboriginal and Torres Strait
Islander Data Archive: Connecting Communities and Research Data.”
Language Documentation and Description 12(Special Issue on Language
Documentation and Archiving): 103–19.

Kornei, K. (2021), Academic citations evolve to include Indigenous
oral teachings, Eos, 102,
[https://doi.org/10.1029/2021EO210595](https://doi.org/10.1029/2021EO210595). Published on 9 November 2021.

MacLeod, L.. 2021. “More Than Personal Communication: Templates For
Citing Indigenous Elders and Knowledge Keepers”. KULA: Knowledge
Creation, Dissemination, and Preservation Studies 5
(1). [https://doi.org/10.18357/kula.135](https://doi.org/10.18357/kula.135).

Mannheimer S, Pienta A, Kirilova D, Elman C, Wutich A. Qualitative
Data Sharing: Data Repositories and Academic Libraries as Key Partners
in Addressing Challenges. American Behavioral
Scientist. 2019;63(5):643-664. doi:10.1177/0002764218784991

Ormond-Parker, L., Sloggett, R. Local archives and community
collecting in the digital age. Arch Sci 12, 191–212
(2012). [https://doi-org.colorado.idm.oclc.org/10.1007/s10502-011-9154-1](https://doi-org.colorado.idm.oclc.org/10.1007/s10502-011-9154-1)

Johnson, Noor, Matthew L. Druckenmiller, Finn Danielsen, and Peter
L. Pulsifer. 2021. “The Use of Digital Platforms for Community-Based
Monitoring.” BioScience 71(5): 452–66.
