---
author: "Amber Budden"
date: "3/4/2022"
---

## Community Data

### Introduction

In this section of the training, we focus on **tools and approaches for
ethically managing community data in research projects and community
collaborations**.

**Community data** can be defined broadly as **any data that a community
feels a sense of investment in or ownership of** (Johnson et al. 2021;
Pulsifer et al. 2012). (In this workshop, we are using the term
“community” to refer to a geographic place and the people who live
there). Community data may include:

 * data produced by community-engaged or led research projects;  
 * data collected by external researchers that is about or relevant to
   a community or the people who live there;
 * or data or information needed to guide local decision-making and
   planning.

How does management of community data differ from traditional academic
approaches to data management? While many of the tools (such as data
management plans) are similar, community data management is guided by
ethical considerations and protocols discussed in the “data ethics”
part of this training. It has been said that data management is not
primarily technical but social; **ethical management of community data
requires significant attention to the processes of meaningful
collaboration needed to build and maintain relationships with
communities**. Community data management also requires an understanding
of the governance context, including ethics protocols. In addition,
building capacity and support for community control of data is an
important aspect of community data management. **ELOKA refers to these
three aspects (governance/application of tools/capacity building) as
comprising a “community data management system.”**


### Tools and Approaches for Stewardship of Community Data

#### Memorandum of Understanding (MOU)

**An MOU is a formal agreement between two or more parties that
documents the nature of the relationship and collaboration and puts
into writing specific expectations regarding data management and data
ownership. [Although they are not legally binding](https://uas.alaska.edu/admin/mous-moas.html)**, they are formal
agreements to coordinate activities and as such, Universities may
require legal counsel to review an MOU. An MOU may be most useful when
a community or Tribe and a research program or institution want to lay
out terms for ongoing collaboration beyond the timeframe of a single
project, although sometimes a more formal agreement may be helpful to
establish clear expectations for cooperation at the project level.

**Some resources and templates for developing an MOU**:

Memorial University. [Indigenous Research Agreement Template](https://www.mun.ca/research/Indigenous/agreement.php). 

Liboiron, M. “[Template of Memorandum of Understanding for Mutual Aid
Research in Disasters.](https://seeingcollaborations.files.wordpress.com/2014/10/template-of-memorandum-of-understanding-for-mutual-aid-research-in-disasters-5-1-12.docx)” Template/resource designed with “mutual-aid
researcher-community or academic-activist partnerships in mind.”

Colorado Nonprofit Association. 2003. [Collaboration Toolkit: Creating an MOU](https://anschutzfamilyfoundation.org/wp-content/uploads/2016/04/MOU-toolkit-MAIN.pdf). 

Indigenous Works, “Building a Memorandum of Understanding” - includes [template](https://indigenousworks.ca/en/resources/articles-reports/mou):

Karuk Tribe. “[Memorandum of Mutual Understandings](https://www.sustainableheritagenetwork.org/system/files/atoms/file/KarukTribe_MemorandumofMutualUnderstanding.pdf).” (Approved to be shared as a resource through the Sustainable Heritage Network).


#### Data Management Plan (DMP)

A DMP is a document used to **describe the strategies and tools you will
use to manage your data through different stages in the research
lifecycle, including data collection, documentation & metadata,
storage and backup, sharing & reuse, and preservation**. The DMP
includes plans for managing data both during active research as well
as after the project is complete. DMPs include information about:

 * what data will be created
 * what policies will apply to the data
 * who will own and have access to the data
 * what data management practices will be used
 * what facilities and equipment will be required
 * who will be responsible for each of these activities.

[https://dmptool.org/](https://dmptool.org/) is a free, online tool
developed by the California Digital Library to guide development of
DMPs. The template is customizable based on the funder that the plan
will be submitted to. They maintain a list of funder requirements as
well as a list of public plans from other projects - you can search
them by keyword, funder, institution, language, and subject. (At the
time of this training, a keyword search for “Indigenous” had only one
result). The tool does not (yet?) incorporate IDS/CARE principles. A
similar tool, [DMPonline](https://dmponline.dcc.ac.uk/), is available from the Digital Curation
Centre.

**A data management plan should be developed during the planning phase
of a research project**. Many funders explicitly require a data
management plan as part of a funding proposal. As a result, DMPs are
often put together in haste to meet a proposal deadline without a lot
of thought about ethical management of data. These DMPs are then often
set aside without a lot more thought, and as a result there is a
missed opportunity to use DMPs to deeply consider data as one of the
major legacies of a research project, with the potential to “live”
well beyond the duration of the research project. **In the context of
collaborative research, data sharing and use have the potential to
create friction when they are viewed as supplementary rather than
integral to good project planning and implementation.**

Some elements of a DMP for co-produced research or research involving Indigenous Knowledge:

 * When Indigenous data is involved or when activities will be
   undertaken on or near Indigenous lands/waters, or when the data
   generated is relevant to Indigenous governance, the plan should
   include a discussion of Indigenous data sovereignty.  
 * This should include a statement of overall intent as well as a
   careful review of proposed activities to ensure that they uphold
   IDS principles, with reference to the relevant ethical guidelines
   including any foundational or mid-level frameworks as well as the
   CARE principles.  
 * The foundational guidelines at the Tribal or community level, if
   available, should serve as the primary resource for ethical data
   management.  
 * To be effective in the context of collaborative research, DMPs
   should be revisited at different stages of the project to make sure
   that all collaborators still feel comfortable with plans based on
   how the project has evolved.  

The [Aboriginal and Torres Strait Islander Data Archive](https://www.atsida.edu.au/) (ATSIDA)
suggests that researchers working in the field of Australian
Indigenous Studies ask and answer (collaboratively with communities)
the following questions as part of data management planning (also
relevant to the Arctic community and Indigenous context):

1. Do the participants want the data preserved?  
2. Does any data need to be attributed to Traditional Knowledge holders?  
3. What are the access and use constraints for data deposited?  
4. How do I manage requests for re-use?  
5. Do I need to make the data anonymous?  
6. Can I publish the material online?  
7. If material is closed to public access, how long for?
8. Do I need to dispose of any research data? If so, have I deleted it
adequately without leaving a digital footprint? (Gardiner and Thorpe
2014)  


#### Data Use Agreement

**A data use agreement is a tool that asks users to agree to specific
requirements for use, such as providing context for the data, citing
the data in a certain way, and recognizing the rights of Indigenous
knowledge holders**. For example, the SIZONet/AAOKH database, a digital
database of community contributed observations about the coastal
environment in Alaska, includes a use agreement that provides a
citation for the dataset and asks users to acknowledge the individual
observer as well as review a paper providing additional context. In
order to access the observations, an atlas user must confirm that they
will abide by these use terms.


#### Suggested Data Citation

#### Metadata

#### Traditional Knowledge Labels and Notices

#### Digital Infrastructure

#### Long-term Storage and Archiving

#### Publishing

#### Secondary Analysis of Indigenous Data

### Summary: Life Cycle of Community Data
