---
title: "data-publishing-part-two-socialsci"
output: html_document
---

## Data Publishing and Documentation, Part Two

### Learning Objectives

In this lesson, we will:
- Summarize data ethics in the context of open science
- Write a statement on ethical considerations of your research
- Peer review these statements

### Open Data and Ethics

The foundation of open-science is based on making all aspects of scientific research accessible across broad communities, whether professional, academic or public. This includes publications, data, software, samples, and code, and at its core, open science is built on principles of transparency and capacity for collective knowledge. The practice of open science is being increasingly adopted by researchers across disciplines, and organizations and working groups such as FORCE11 promote and support this through development of principles and guidelines that inform activities. While open-science affords researchers the opportunity to extend the reach of their work (Puebla & Lowenberg, 2021) and increases transparency and public trust, such transparency creates challenges for those researchers working with sensitive data and Indigenous knowledge. Open science principles are informed largely by western knowledge concepts and do not consider Indigenous data sovereignty and Indigenous Knowledge (Research Data Alliance International Indigenous Data Sovereignty Interest Group, 2019).

Transparency in data ethics is a vital part of open science. Regardless of discipline, various ethical concerns are always present, including professional ethics such as plagiarism, false authorship, or falsification of data, to ethics regarding the handling of animals, to concerns relevant to human subjects research. Sharing ethical practices openly, similar in the way that data is shared, enables deeper discussion about data management practices, data reuse, sensitivity, sovereignty and other considerations. Further, such transparency promotes awareness and adoption of ethical practices. As the primary data repository for the National Science Foundation Office of Polar Programs Arctic Sciences section, the Arctic Data Center accepts data from all disciplines including social science and other research that may be subject to IRB restrictions, involve Indigenous knowledge, or have been carried out on Indigenous lands. Researchers submitting data now have the opportunity to articulate these and other considerations as part of the metadata record. First, researchers can identify the level of sensitivity that best represents the dataset from one of three sensitivity data tags ranging from non-confidential information to maximally sensitive information that best fit their data and/or metadata. Based on the level of sensitivity, guidelines and next steps for data submission are provided. 

## Activity and Discussion 

1. Fill out the ethical research considerations form (linked here)
2. In breakout groups, consider the following questions:
* Were there any differences between the first version of the ethical considerations, and the second version?
* What ethical considerations are the most relevant in your research, and why?
* How can principles such as the CARE principles, be adopted into your research?



