## Learning Objectives {.unnumbered}

## What is Synthesis Science?

Synthesis science is the process of distilling existing data, ideas, theories, or methods drawn from many sources, across multiple fields of inquiry, to accelerate the generation of new scientific knowledge, often at a broad scale.

Research in ecological and environmental sciences is often inherently complex and well-suited to synthesis approaches. It is a key approach for understanding complexity across scales, leveraging data from various disciplines, facilitating discovery of general patterns in natural systems, and informing policy.

In synthesis research, it is also vital to consider and increase diversity of participants and to foster inclusive research environments. When diveristy and inclusion is not prioritized, syntheses risk being biased and less broadly applicable, which may lead to unjust and inequitable outcomes. Although the principles of diversity and inclusion are relevant to any scientific endeavor, they are particularly salient for synthesis given its integrative nature.

### Conceptual Synthesis

### Meta-Analysis Synthesis

### Data set Synthesis

## NCEAS and Synthesis Science

## NCEAS Case Studies

### OHI

### SASAP

## Future of Synthesis

In February 2021, NCEAS hosted a virtual workshop where 127 ecologists, environmental and natural scientists convened to discuss the future priorities of synthesis science. Participants across career stages, institutions, backgrounds, and geographies were in attendance. 

Participants proposed ideas or questions in pre-workshop brainstorming sessions; added and upvoted questions online; and worked in breakout teams during the workshop to refine upvoted questions into lists of top three questions. These final lists were then grouped into themes by the 12-person steering committee and discussed at length by the workshop participants.

In January 2023, over dozens of scientists authored and published [Priorities for synthesis research in ecology and environmental science](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.4342#ecs24342-bib-0004) the results of the workshop. 

Seven priority research topics emerged: (1) diversity, equity, inclusion, and justice (DEIJ), (2) human and natural systems, (3) actionable and use-inspired science, (4) scale, (5) generality, (6) complexity and resilience, and (7) predictability. Additionally, two issues regarding the general practice of synthesis emerged: the need for increased participant diversity and inclusive research practices; and increased and improved data flow, access, and skill-building. 

## Best Practices?


