---
format: html
---

## Learning Objectives {.unnumbered}

- Develop synthesis research ideas to pursue as a group with the potential of producing synthesis research products (e.g. high impact publication)
- Discuss synthesis research ideas as a group and iterate to a focused research question
- Develop community norms to guide synthesis ideas generation and iteration

## Synthesis Research Questions Rounds

::: {.callout-tip collapse="true" icon="false"}
### Round 1: Question Everything

Go to each synthesis research question and add all the questions you have about this topic. No question is too basic here! The goal is to ask all kinds of questions from varying perspectives to gain different understandings about the topic.

*Example:* 

:::

::: {.callout-tip collapse="true" icon="false"}
### Round 2: Narrow it Down

Go to each synthesis research question and review the questions that have been added to it from the first round. Consider how you would make this question actionable with a reasonable scope. What are potential outcomes or research products?

*Example:* 

:::

::: {.callout-tip collapse="true" icon="false"}
### Round 3: Choose Your Adventure

Time to choose a topic and synthesis research question you want to work on! You are not picking a broad question or topic to work on, instead you are selecting one of the refined questions within the broad question. Additionally consider what skills, expertise, and people would be needed to successfully complete this project.

*Example:* 

:::

## Leadership User Manual

::: {.callout-note}
### Acknowledgements
The Leadership User Manual is an idea that has long been adapted by multiple organizations, businesses, and academic institutions. See articles in [Forbes](https://www.forbes.com/sites/kevinkruse/2018/07/01/how-to-create-your-leadership-users-manual/?sh=792755137a4d), [The New York Times](https://www.nytimes.com/2013/03/31/business/questbacks-lead-strategist-on-his-user-manual.html), and [LinkedIn](https://www.linkedin.com/pulse/20140106124338-35894743-what-if-you-had-to-write-a-user-manual-about-your-leadership-style/).
:::

A Leadership User Manual is a guide to share with your team and collaborators so they best know how to work with you. You can think of it as a reflection exercise on your strengths and weaknesses, working style, quirks, and any additional information that encompasses your working personality.

::: {.callout-caution appearance="minimal"}
[View an example](https://drive.google.com/file/d/1idSatpLL5Or3JMA-7m4pTiBZdMPCgLIU/view?usp=drive_link) created by Danielle Furuichi, an alum from University of Colorado Boulder, who developed a Leadership User Manual for their capstone group.
:::

### Exercise:

Use the [provided template](https://docs.google.com/document/d/1nsR5lxcDm0SH7ME-iRgUrssynCghww2LnHVdLo_dWLE/edit?usp=sharing) to create your own Leadership User Manual. Then share with your collaborators, and learn about your collaborators through their Leadership User Manuals.


