---
format: html
---

## Learning Objectives {.unnumbered}

- Apply design thinking approaches and tools to dashboard development
- Evaluate whether to build a web application using `flexdashboard` or `shiny`
- Practice developing a web application using `flexdashboard` or `shiny`


::: {.callout-note icon=false}
### Acknowledgements
Women in Data Science (WiDS) Workshops: [Dashboard Design Thinking by Jenn Schilling](https://youtu.be/xd-V-ikReDI?si=hrX3TUS4MSVL3tn-)
:::

## What is Design thinking?

Design thinking in data science centers the user's perspective throughout the entire development of a dashboard. It starts with the user by gaining an understanding on what the user needs and ends with the user by involving them in focus groups or other testing methods to get their feedback. By focusing on the user we can create better dashboards and improve our audience's ability to make data-informed decision making. 

Design thinking is inherently an innovative and collaborative process because it involves exploring multiple options for the same problem. 

The design thinking process can be encapsulated within these stages:

1. **Empathize and Define**: In these stages, we use tools to understand the problem and our audiences.
2. **Ideate and Prototype**: We use these stages to explore solutions.
3. **Test and Implement**: In these final stages, we use tools to materialize the final product.

These stages are not meant to be in any particular order. While there is an inherent order to them, you should feel empowered to move between the stages as needed --- depending on the development of your dashboard and the needs of your users.


## Empathize and Define

::: {.callout-caution appearance="minimal"}
***Empathize***: *Gather information and survey your users to understand what they need to know from the data, what are the use cases for the dashboard and its overall purpose.*
:::

### Empathize Tools: Empathy Mapping {.unnumbered}

During the Empathize stage, you can gather information through internal conversations with your team or conduct interviews with potential users.

The **goal of an Empathy Map** is to capture what a user says, thinks, does, and feels --- additionally consider what their goals are (*and do their goals align the goals you have in mind for the dashboard you're developing?*).

::: {.callout-caution appearance="minimal"}
***Define***: *Identify the core problems your users have in accessing and interpreting the data in its current state.*
:::

### Define Tools {.unnumbered}



## Ideate and Protoype

::: {.callout-caution appearance="minimal"}
***Ideate***: *Challenge your existing assumptions and create ideas. Look for alternative ways to view the problem and identify solutions.*
:::

### Ideate Tools {.unnumbered}

- brainstorm
- mind mapping

::: {.callout-caution appearance="minimal"}
***Prototype***: *Start to create the solutions. It's important to experiment here. Produce some inexpensive and low-intensive versions of the product.*
:::

- use flexdashboard to create a lightweight version of a shiny app

## Test and Implement

::: {.callout-caution appearance="minimal"}
***Test***: *Try your solutions and evaluate the results. Return to your users for feedback to incorporate.*
:::

### Test Tools {.unnumbered}


::: {.callout-caution appearance="minimal"}
***Implement***: *Put your vision into effect! Remember that the process doesn't have to end here at implementation. Return to your users to gain more feedback and to guide the refinement of your solutions.*
:::

### Implement Tools {.unnumbered}



