name: Dispatcher

on:
  push:
    branches: ['**']
  pull_request:
    types: [closed]
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name from pull request
      id: extract_branch
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
    - name: Dispatch to RRC
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.RRCOURSE }}" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        --data "{"event_type": "quarto", "ref": "develop", \"branch\": \"$BRANCH\"}" \
        https://api.github.com/repos/nceas/repro-research-course/dispatches \
