name: Dispatcher

on:
  push:
    branches: ['**']
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:   
    - name: Check name of branch
      run: |
        echo $GITHUB_HEAD_REF
    - name: Dispatch to RRC
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.RRCOURSE }}" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        --data "{"event_type": "quarto", "client_payload": {"branch": "$GITHUB_HEAD_REF"}}" \
        https://api.github.com/repos/nceas/repro-research-course/dispatches \
