name: Dispatcher

on:
  push:
    branches: ['**']
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:   
    - name: Check name of branch
      run: |
        echo $GITHUB_REF_NAME
        
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.RRCOURSE }}
        repository: nceas/repro-research-course
        event-type: quarto
        client-payload: '{"branch": "${{ GITHUB_REF_NAME }}"}'
