name: invoke build in gha-website-test

on:
  push:
    branches: ['**']
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/github-script@v6
      with:
        github-token: '${{ secrets.RRUSER}}:${{secrets.RRCOURSE}}'
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'NCEAS',
            repo: 'repro-research-course',
            workflow_id: 'workflow.yml',
            ref: 'master',
            inputs: {
              event_type: 'quarto',
              branch: $GITHUB_HEAD_REF
            }
          })
