# Webook to build course website

name: webhook
on: 
  workflow_dispatch:
  push:
    branches: [ '**' ]

        
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: renderbook
          repo: nceas/repro-research-course
          ref: master
          token: ${{ secrets.RRCOURSE }}
