name: Dispatcher

on:
  push:
    branches: ['**']
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:   
    - name: Check name of branch
      run: |
        echo $GITHUB_REF
        
    - name: Dispatch to RRC
      run: |
          curl -XPOST -u "${{ secrets.RRUSER}}:${{secrets.RRCOURSE}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/nceas/repro-research-course/dispatches --data '{"event_type": "bookdown"}'
