name: Dispatcher

on:
  push:
    branches: ['**']
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:   
    - name: Check name of branch
      run: |
        echo $GITHUB_REF_NAME
        
    - name: Dispatch to RRC
      run: |
        echo '{"event_type": "quarto", "client_payload": {"branch": $GITHUB_REF_NAME}}'
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{ secrets.RRCOURSE }}" \
        https://api.github.com/repos/nceas/repro-research-course/dispatches \
        -d '{"event_type": "quarto", "client_payload": {"branch": $GITHUB_REF_NAME}}'
