project:
  type: book
  output-dir: _book
  
book: 
  title: "Fundamentals in Data Management for Qualitative and Quantitative Arctic Research"
  subtitle: "January 27-31, 2025"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2025-01-arctic
  
  chapters:
    - index.qmd # preface 
    - session_01.qmd # ADC intro
    - session_02.qmd # R Setup 
    - session_03.qmd # Intro to R programming
    - session_04.qmd # Thinking preferencees + Social aspects of collab
    - session_05.qmd # DMP
    - session_06.qmd # Literate analysis
    - session_07.qmd # ADC-Fundamental practice 1 
    - session_08.qmd # Data Modeling and Tidy Data
    - session_09.qmd # Cleaning and Wrangling
    - session_10.qmd # Intro Data Viz
    - session_11.qmd # Ethical Data Collection
    - session_12.qmd # ADC-Fundamentals practice 2
    - session_13.qmd # Text data
    - session_14.qmd # Census data
    - session_15.qmd # Metadata best practices & publishing
    - session_16.qmd # Data portals
    - session_17.qmd # Survey Workflows
    - session_18.qmd # Repro and Provenance
  

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual
