project:
  type: book
  output-dir: _book
  
book: 
  title: "UCSB Faculty Seminar Series: Grow Your Data & Team Science Skills"
  # date: "January 22-26, 2024"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2024-03-ucsb-faculty
  
  chapters:
    - index.qmd # preface 
    - session_01.qmd # Intro and Lego
    - session_02.qmd # Data Visualization
    - session_03.qmd # Text Analysis (Casey)
    - session_04.qmd # Survey data
    - session_05.qmd # Visualizing spatial data (Rachel)
    - session_06.qmd # Quarto Dashboards
    - session_07.qmd # Practice Session
    - session_08.qmd # Message Box
    - session_09.qmd # Publishing to Web
    - session_10.qmd # GitHub Workflows
    - session_11.qmd # GitHub for project management
    - session_12.qmd # reproducibility and provenance
    - session_13.qmd # check PAT
    # - session_14.qmd # Social Aspects of collab
    # - session_15.qmd # Functions
    # - session_16.qmd # Packages
    # - session_17.qmd # Practice Session II
    # - session_18.qmd # Data Portals
    # - session_19.qmd # Spatial Data
    # - session_20.qmd # Repro and Provenance
    
  

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual