project:
  type: book
  output-dir: _book
  
book: 
  title: "Reproducible Approaches to Arctic Research Using R"
  # date: "January 22-26, 2024"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2024-02-arctic
  
  chapters:
    - index.qmd # preface 
    - session_01.qmd # ADC intro
    - session_02.qmd # r setup 
    - session_03.qmd # Literate analysis
    - session_04.qmd # DMP + Documenting and publishing data
    - session_05.qmd # Intro to Git
    - session_06.qmd # data modeling essentials
    - session_07.qmd # Cleaning and Wrangling 
    - session_08.qmd # collaborating with git
    - session_09.qmd # publising to the web
    - session_10.qmd # intro data viz
    - session_11.qmd # practice session
    - session_12.qmd # Data Portals
    - session_13.qmd # Social Aspects of collab
    - session_14.qmd # Functions and Packages
    - session_15.qmd # Practice Session
    - session_16.qmd # Spatial Data
    - session_17.qmd # Repro and Provenance
    - session_18.qmd 
  

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual