project:
  type: book
  output-dir: _book
  
book: 
  title: "UCSB Faculty Seminar Series: Grow Your Data & Team Science Skills"
  # date: "April 3, 2023"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2023-08-usgs
  
  chapters:
    - index.qmd # preface
    - session_01.qmd # synthesis generation & iteration
    - session_02.qmd # team science essentials
    - session_03.qmd # intro to R programming
    - session_04.qmd # fair & care
    - session_05.qmd # writing DMPs UCSB Library 
    - session_06.qmd # intro to literate analysis
    - session_07.qmd # tidy data
    - session_08.qmd # accessing & finding data UCSB DREAM Lab
    - session_09.qmd # intro `Git` & GitHub
    - session_10.qmd # clean wrangle data
    - session_11.qmd # collab `Git` & GitHub
    - session_12.qmd # appendix: RStudio server setup + Git & GitHub setup
    

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual