project:
  type: book
  output-dir: _book
  
book: 
  title: "NCEAS Open Science Synthesis for the Delta Science Program"
  # date: "April 3, 2023"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2023-10-delta
  
  chapters:
    - index.qmd # preface
    - session_01.qmd # census maps
    - session_02.qmd # message box
    - session_03.qmd # synthesis
    - session_04.qmd # flexdashboard
    - session_05.qmd # shiny
    - session_06.qmd # practice: shiny + flexdashboard using design thinking
    - session_07.qmd # synthesis
    - session_08.qmd # reproducible workflows using targets
    - session_09.qmd # parallel processing
    - session_10.qmd # synthesis
    - session_11.qmd # publishing data
    - session_12.qmd # git workflows
    - session_13.qmd # synthesis
    - session_14.qmd # presentations and wrap-up
    

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual