project:
  type: book
  output-dir: _book
  
book: 
  title: "NCEAS Learning Hub’s coreR Course"
  subtitle: "October  - 11, 2024"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2024-10-coreR
  
  chapters:
    - index.qmd # preface 
    - session_01.qmd # Introduction
    - session_02.qmd # R Setup
    - session_03.qmd # Git and GitHub set up
    - session_04.qmd # Intro to R & RStudio
    - session_05.qmd # Literate Analysis
    - session_06.qmd # Lego Activity + Discussion
    - session_07.qmd # Intro to Git and GitHub
    - session_08.qmd # Tidy Data
    - session_09.qmd # Cleaning and Wrangling
    - session_10.qmd # Practice Session I - joins
    - session_11.qmd # Collaborating with Git 
    - session_12.qmd # Publishing to the Web
    - session_13.qmd # Intro to Data Viz
    - session_14.qmd # Practice Session II -lobter report 
    - session_15.qmd # Data Management
    - session_16.qmd # Spatial Data
    - session_17.qmd # Functions and Packages
    - session_18.qmd # Practice Functions and Packages
    - session_19.qmd # Office Hour Guidelines
    - session_20.qmd # GitHub for Project management
    - session_21.qmd # Repro and Provenance
    # - session_22.qmd # Appendix: Set up in personla comp
    
  

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual