project:
  type: book
  output-dir: _book
  
book: 
  title: "NCEAS Open Science Synthesis for the Delta Science Program"
  # date: "April 3, 2023"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Course Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2023-06-delta
  
  chapters:
    - index.qmd # preface
    - session_01.qmd # collaborating using git & github and merge conflicts
    - session_02.qmd # social aspects of collaboration
    - session_03.qmd # thinking preferences
    - session_04.qmd # synthesis
    - session_05.qmd # publishing to web
    # - session_06.qmd # data vis
    - session_07.qmd # systematic reviews
    - session_08.qmd # synthesis
    # - session_09.qmd # spatial data
    - session_10.qmd # intro to meta-analysis
    - session_11.qmd # text data
    - session_12.qmd # census data
    - session_13.qmd # reproducible surveys
    - session_14.qmd # spatial demographis specialist
    - session_15.qmd # synthesis
    - session_16.qmd # shiny
    - session_17.qmd # 2FA setup
    

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual