project:
  type: book
  output-dir: _book
  
book: 
  title: "NCEAS coreR for Delta Science Program"
  subtitle: "June 10 - 13, 2024"
  reader-mode: false
  
  # NoteHD: cover image is not working
  # cover-image: cover.png
  # cover-image-alt: "Learning Hub logo in the shape of a hexagon with a bee in the center"
  
  favicon: cover.png # learning hub logo
  
  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/NCEAS/nceas-training/tree/2024-06-delta
  
  chapters:
    - index.qmd # preface 
    - session_01.qmd # Introduction
    - session_02.qmd # R Setup
    - session_03.qmd # Git and GitHub set up
    - session_04.qmd # Literate Analysis
    - session_05.qmd # Intro to Git and GitHub
    - session_06.qmd # Data Modeling Essentials 
    - session_07.qmd # Cleaning and Wrangling
    - session_08.qmd # Practice Session I - joins
    - session_09.qmd # Collaborating with Git
    - session_10.qmd # Data Management
    - session_11.qmd # Publishing to the Web
    - session_12.qmd # Intro to Data Viz
    - session_13.qmd # Spatial Data
    - session_14.qmd # Practice Session II -lobter report 
    - session_15.qmd # Shiny
    - session_16.qmd # Reproducibility and Provenence
    - session_17.qmd # Appendix: Set up in personla comp
    # - session_18.qmd # Data Portals
    # - session_19.qmd # Spatial Data
    # - session_20.qmd # Repro and Provenance
    
  

bibliography: book.bib
      
format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

editor: visual