# Getting the Most out of Collaborative Science

## Learning objectives

In this lesson you will learn

* What conditions enable successful interdisciplinary and intersectoral collaboration

* How to strengthen the structures, processes, and mindsets that support team science collaboration

* How to build capacity within your teams and the broader system for more effective collaboration, facilitation, and principles-based convening

    2. Characteristics of effective teams

    * Right size

    * Right people

    * Aligned purpose and incentives

    * Effective organizational structure

    * Strong individual contributions

    * Supportive team processes

See Micken and Rodger 2000 in the Resources below for more detail.

## Aligning around shared purpose and a clear work plan

Coming to a shared definition of success and understanding of the project scope is critical for success. It may be useful to write a short manifesto that articulates what you are doing, why and how.

Once the purpose is clear, then you need a clear work plan and timeline that articulates the group’s work streams and the roles, responsibilities and tasks of group members. Tools that can help support this include:

* [Responsibility assignment matrix (RACI)](https://en.wikipedia.org/wiki/Responsibility_assignment_matrix)

* [Gantt Chart](https://en.wikipedia.org/wiki/Gantt_chart)

There are many free online templates available for these, as well as various project management software platforms. Whatever you use, make it accessible to all team members so everyone can record and track progress. What is most important is to select a system that the majority of your team members are likely to use. If there is already momentum toward a particular tool or platform, your best bet is probably to go with that momentum rather than try to institute a new practice or tool. 

## Culture and leadership

The success of a working group or other team science endeavor hinges on a good collaborative culture emerging within the group, and interactions early on help set expectations and direction. The meeting chair and/or facilitator can use signposting language (e.g., "We want your input on our goals and work plan so we can get to a shared vision of where we’re headed.") and structures for interaction (e.g., those that invite participation by everyone) to set the tone.

Some elements of this culture include:

* Mutual respect, trust, and opportunities for human connection

* Clear norms and expectations, e.g. for how conflicts will be handled and how credit will be shared and attributed

* Clear data sharing and authorship guidelines: If your group spans diverse fields and/or sectors, members may have divergent perspectives, so it’s important to talk about this openly early in the process

* Equal opportunities for participation that welcome all voices and contributions

* Sharing facilitation responsibilities: Each activity should have an objective. The duty of keeping the group on track toward those objectives can be rotated.

## Traditional and network mindsets

Collaborative work requires us to move in and out of what is known as a network mindset (versus a traditional mindset, which might apply, for example in a traditional lab setting). It is the network mindset that sees the potential for greater than the sum of the parts solutions. Orienting from a network mindset we lean into uncertainty, trusting that useful outcomes may emerge from the collective intelligence of the network. Those outcomes include enhanced learning, new ideas, and new opportunities for collaborative research. It’s important to note, though, that there is a place for both the traditional and the network mindset. Neither is better than the other. The skill comes in knowing when one or the other is required and moving easily between them. 

<table>
  <tr>
    <td>Traditional Mindset</td>
    <td>Network Mindset </td>
  </tr>
  <tr>
    <td>Hierarchical </td>
    <td>Horizontal </td>
  </tr>
  <tr>
    <td>Firmly controlled and planned</td>
    <td>Loosely controlled and emergent</td>
  </tr>
  <tr>
    <td>Centralized authority</td>
    <td>Distributed authority</td>
  </tr>
  <tr>
    <td>Task Oriented</td>
    <td>Relationship Oriented</td>
  </tr>
  <tr>
    <td>Production of products and services </td>
    <td>Cultivation of learning and activity </td>
  </tr>
  <tr>
    <td>Strengthening individual efforts</td>
    <td>Weaving connections and building networks </td>
  </tr>
  <tr>
    <td>Proprietary information and learning </td>
    <td>Open information and learning</td>
  </tr>
  <tr>
    <td>Decision making concentrated</td>
    <td>Decision making shared / transparent</td>
  </tr>
  <tr>
    <td>Individual intelligence and achievement</td>
    <td>Collective intelligence and action </td>
  </tr>
  <tr>
    <td>Effectiveness linked to concrete outputs</td>
    <td>Effectiveness also linked to intangibles (trusting relationships, information flows)</td>
  </tr>
  <tr>
    <td>Credit claimed by individual or single organization</td>
    <td>Credit shared with partners</td>
  </tr>
  <tr>
    <td>Conflict averse</td>
    <td>Conflict acknowledged and addressed</td>
  </tr>
</table>


*Adapted from Monitor Institute & Rockefeller Foundation, ENGAGE*

## Resources

Micken and Rodgers. 2000. Characteristics of effective teams: A literature review. Australian Health Reviews

