# Finding help 


## From within R

* `?...`, `help(...)` : help for a specific function (you know the name of it)
* `??...`, `help.search(...)` (or `help.search(...,agrep=FALSE)` to avoid partial matching): includes packages and partial matching


## Task views

* Task views (or [this view](http://www.maths.lancs.ac.uk/~rowlings/R/TaskViews/) )
    * [Environmetrics](http://cran.r-project.org/web/views/Environmetrics.html)
    * [Phylogeny/comparative methods](http://cran.r-project.org/web/views/Phylogenetics.html)
    * [High-performance](http://cran.r-project.org/web/views/HighPerformanceComputing.html)
    * [Spatial](http://cran.r-project.org/web/views/Spatial.html)
    

## RStudio Website

- Cheat Sheets: https://rstudio.com/resources/cheatsheets/   (Also from RStudio IDE -> Help -> Cheatsheets)
- Books: https://rstudio.com/resources/books/
- Webinar series: https://resources.rstudio.com/




## Solving  problems

There are 2 big categories of errors:

1. The code will not run (aka R is complaining... like a lot) 
2. The code is running, but the results are erroneous (the hardest one to solve)

### Do it yourself

Few strategies:

- try to reproduce the problem
- break it down to narrow the problematic piece of code (the [degugger](https://adv-r.hadley.nz/debugging.html) can help you)
- try with a small sample dataset
- try with a test dataset you built to test edge cases

### Search Forums, blogs, ...

* Google :)
* StackExchange <https://stackexchange.com/> and the more known StackOverflow <https://stackoverflow.com/>
* RStudio  <https://education.rstudio.com/> and its community website <https://community.rstudio.com/>
* RopenSci <https://ropensci.org/about/>
* r-bloggers
* Twitter: `#rstats`


### Posting a question

It is recommended to provide a reproducible example when posting a question on a forum. [`reprex`](https://reprex.tidyverse.org/) is a great R package to help you to do so. 

**Most of the time, creating a reproducible example on a data sample will help you to solve your problem on your own**

## Communities

* Friends and colleagues
* Local user groups: [R User Groups](https://www.r-consortium.org/projects/r-user-group-support-program), [R-ladies](https://rladies.org/) on Meetup
* Universities (e.g. [Software Carpentry workshops](https://software-carpentry.org/))

## NCEAS

NCEAS computing team is here to advise and support your working group!

For data science questions: SciComp@nceas.ucsb.edu

For technical questions: help@nceas.ucsb.edu

For KNB questions: knb-help@nceas.ucsb.edu
