--- 
title: "NEON Onboarding Materials"
date: "Published December 2020"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: ""
always_allow_html: yes
---

# Overview {-}

Placeholder


## Rationale {-}
## About this resource {-}
## Acknowledgements {-}

<!--chapter:end:index.Rmd-->

# Working at NEON

```{r, child = 'sections/working-at-neon.Rmd'}
```

<!--chapter:end:session_01.Rmd-->

# Preparing for Success

```{r, child = 'sections/individual-development-plan.Rmd'}
```

<!--chapter:end:session_02.Rmd-->


# Team Science

Placeholder


## Collaboration Practices

<!--chapter:end:session_03.Rmd-->

# Communicating Your Research

```{r, child = 'sections/communication.Rmd'}
```

---

```{r, child = 'sections/collaboration-social-data-policies.Rmd'}
```


<!--chapter:end:session_04.Rmd-->

# Reproducible Research Techniques - Data Training

```{r, child = 'sections/data-management-plans-reduced.Rmd'}
```

---

```{r, child = 'sections/r-intro-rstudio-git-setup-motivation.Rmd'}
```

---

```{r, child = 'sections/metadata-data-best-practices-intro.Rmd'}
```

---

```{r, child = 'sections/metadata-knb-data-documentation-hands-on.Rmd'}
```

---

```{r, child = 'sections/r-introduction-to-rmarkdown.Rmd'}
```

---

```{r, child = 'sections/git-intro.Rmd'}
```

---

```{r, child = 'sections/git-collaboration-conflicts.Rmd'}
```

---

```{r, child = 'sections/data-modeling.Rmd'}
```

---

```{r, child = 'sections/data-cleaning-manipulation-tidyverse.Rmd'}
```

---

```{r, child = 'sections/git-github-publishing-analysis.Rmd'}
```

---

```{r, child = 'sections/r-creating-functions.Rmd'}
```

---

```{r, child = 'sections/r-creating-packages.Rmd'}
```

---

```{r, child = 'sections/d1-creating-data-portals.Rmd'}
```

---

```{r, child = 'sections/exercise-data-cleaning-manipulation-tidyverse.Rmd'}
```

---

```{r, child = 'sections/geospatial-vector-analysis.Rmd'}
```

---

```{r, child = 'sections/provenance-reproducibility-datapaper.Rmd'}
```


<!--chapter:end:session_05.Rmd-->

