---
title: "Data Management and Reproducibility"
title-block-banner: true

---

<iframe width="560" height="380"src="https://docs.google.com/presentation/d/1LKanKcsnhOHunpeKuoS2__TQQ4wR7Gt2VBH-8qD-PJM/preview"allowfullscreen></iframe>



### Workshop Description {.unnumbered}
Computational tools make it easier than ever to collect, analyze, and share data and results in transparent and reproducible ways. To achieve reproducibility, it is important to set systems in place and manage data thoroughly. Data management is the process of handling, organizing, documenting, and preserving data used in a project/research. It helps your research outcomes be transparent, maximizing your work’s practical use and value. This lesson provides an overview of all the meaningful steps in a research project and dives into how to plan for successful data management. We will also discuss tools and systems to help you organize and document your work for better reproducibility, to make your analysis robust, and to facilitate collaboration (including with yourself).


### Learning Objectives{.unnumbered}
-   Understand the importance and benefits of data management and data management plans.
-   Apply the Data Life Cycle steps to organize and plan a research project.
-   Introduce tools and techniques for establishing reproducible analytical workflows.
-   Discuss why we should aim for reproducibility and its importance for collaboration.


:::callout-important
## Missed the training?

Find the video recording of this workshop in this [link](https://drive.google.com/file/d/1M2c09WULjgGuHW26740YIMBm0vpriSFC/view?usp=sharing).

:::



### Resources {.unnumbered}

- [The Research Data Management Workbook](https://caltechlibrary.github.io/RDMworkbook/) by Kristin Briney
- Data inventory [spreadsheet template](https://docs.google.com/spreadsheets/d/1mftmoNPzGMhQehC7iVD5B0D0-Hfh_PNjbY7d9UTh98Y/edit?gid=0#gid=0)
- Documenting Things: Openly for Future Us, by Julia Stewart Lowndes at posit::conf(2023). [Slides](https://openscapes.github.io/documenting-things/#/title-slide) & [Recording](https://www.youtube.com/watch?v=OVM5Ok7W1NQ)
- Ocean Health Index Documentation: [Methods](https://oceanhealthindex.org/images/htmls/Supplement.html#1_Introduction_to_the_global_Ocean_Health_Index_(OHI)_assessment) and [SOP for data management](https://ohi-science.org/ohiprep_v2023/Reference/SOP_dataOrganization/dataOrganization_SOP.html)
- Arctic Data Center [data policy template](https://docs.google.com/document/d/16wNpk9vJiWqQQStmaEG66YgawU39hGC8x9KnbUqbyO4/edit#heading=h.gnbwiz3v0o8z)
- LTER Working Group [README template](https://github.com/lter/lterwg-template)





