---
title: "GitHub for Project Management"
title-block-banner: true
code-annotations: hover
---


<br>


<iframe width="560" height="380"src="https://docs.google.com/presentation/d/1DBBxIa7rE2ULDL32MfJ-AXQdR6F1vN1vD8H4AEnwyfU/preview"allowfullscreen></iframe>


<br>


### Workshop Description {.unnumbered}
GitHub is mainly known as a version control platform that facilitates collaborative coding. Effective collaboration (with yourself or colleagues) requires good communication. GitHub offers several features that can support communication and project management. During this workshop, we will discuss and practice structuring a GitHub repository, taking advantage of GitHub Issues and Projects. 

### Learning Objectives {.unnumbered}
- Briefly introduce Git and GitHub
- Provide an overview of a GitHub Repository
- Understand how GitHub can serve as a Project Management tool
- Know how to create and leverage GitHub Issues
- Be familiar with how to set up and customize GitHub Projects


:::callout-important
## Missed the training?

Find the video recording of this workshop in this [link](https://drive.google.com/file/d/1VwvMOu2MeM0nKvEX5wzJ8n3KvCB9XRS3/view?usp=drive_link).

:::



### Resources  {.unnumbered}

- [Openscapes GitHub for Project Management (Champion Series)](https://openscapes.github.io/series/core-lessons/github/github-issues.html)
- [Openscapes GitHub Clinic slides](https://docs.google.com/presentation/d/1geUN-dv-NMx6IgeCwMRVmTO8nZaauIl26tZDOrkLW_E/edit#slide=id.g20695b6755c_0_0)
- LTER SciComp Workshops, [GitHub Issues](https://lter.github.io/workshop-github/issues.html) & [GitHub Projects](https://lter.github.io/workshop-github/projects.html)
- GitHub Documentation: [Issues](https://docs.github.com/en/issues) & [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects).


