---
title: " Facilitating a successful working group"
title-block-banner: true
format:
  html:
    code-overflow: wrap
---



<div style="display: flex; justify-content: center;"> 
<iframe width="560" height="380" src="https://docs.google.com/presentation/d/1VCRV2htljOrSUkW3Fvjl2rwkm-TNR-9LRn-tS2_2CGY/preview?" frameborder="0" allowfullscreen></iframe>
</div> 

### Workshop Description {.unnumbered}

Learn how to effectively manage a working group from before the first meeting, during the first meeting, and what comes next. We will discuss how to align expectations, general tips on communicating with the team, and what to expect from the working group process. This workshop will also touch on project management and facilitation tips with plenty of time to ask questions to our professional facilitators.

### Learning Objectives {.unnumbered}

-   Become familiar with best practices for running a successful and productive working group from start to finish
-   Familiarize yourself with the fundamentals of good team communication and collaboration
-   Learn tips and tricks for team facilitation and moving through difficult discussions
-   Establish understanding of the working group process, logistics, and management as well as what makes - NCEAS-style working groups most successful

### Key Resources {.unnumbered}

-   NCEAS’ [Resources for Working Groups](https://www.nceas.ucsb.edu/working-group-resources) webpage

-   NCEAS’ [Guide to successful scientific working groups](https://docs.google.com/document/d/1HupL2BNiew-L3LdqOFSD85_qpMdPB7I_zXeXly0tuPY/edit)

-   NCEAS’ [Checklists! for successful scientific working groups](https://docs.google.com/document/d/1HupL2BNiew-L3LdqOFSD85_qpMdPB7I_zXeXly0tuPY/edit)

-   [Liberating Structures](https://www.liberatingstructures.com/ls-menu) for facilitation 
