---
title: "Collaborative Synthesis: Authorship Guidlines & Data Ploicy"
title-block-banner: true
---

<!--{{< include /sections/programmatic-data-access.qmd >}}-->

::: callout-tip
## Team Collaboration Guidelines

1.  Developing a code of conduct

-   Set of shared agreements about how people in the group will treat each other will help create the conditions for successful collaboration.
-   What behaviors do you want to encourage?
-   What behaviors that will not be tolerated?

See examples in [the book](https://learning.nceas.ucsb.edu/2023-08-delta/session_06.html#developing-a-code-of-conduct)

2.  Establishing Authorship and Credit Policies

-   Check the [International Committee of Medical Journal Editors guidelines for authorship and contribution](https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html)
-   Revise the [NISO Contributor Roles Taxonomy (CRediT)](https://credit.niso.org/)
-   As a group answer the following questions relevant questions to your project: What are our criteria for authorship? (See the ICMJE guidelines for potential criteria)
    -   Will we extend the opportunity for authorship to all group members on every paper or product?
    -   Do we want to have an opt in or opt out policy? (In an opt out policy, all group members are considered authors from the outset and must request removal from the paper if they don't think they meet the criteria for authorship)
    -   Who has the authority to make decisions about authorship? Lead author? PI? Group?
    -   How will we decide authorship order?
    -   In what other ways will we acknowledge contributions and extend credit to collaborators?
    -   How will we resolve conflicts if they arise?

3. Data Sharing and Reuse Policies

- Go over the Arctic Data Center Data Sharing and Reuse Policies Example [template](https://docs.google.com/document/d/16wNpk9vJiWqQQStmaEG66YgawU39hGC8x9KnbUqbyO4/edit#heading=h.gnbwiz3v0o8z)
- Use this template to start drafting a Data Sharing and Reuse Policies for your group.

:::
